import {
  Cpu,
  FlaskConical,
  Plane,
  UtensilsCrossed,
  Dumbbell,
  Music,
  Film,
  BookOpen,
  Gamepad2,
  Palette,
  Briefcase,
  HeartPulse,
  Shirt,
  TreePine,
  Landmark,
  Camera,
  GraduationCap,
  Megaphone,
  Laugh,
  PawPrint,
  type LucideIcon,
} from "lucide-react";
import type { InterestType } from "@/types";

export const INTERESTS: Record<InterestType, { label: string; icon: LucideIcon }> = {
  technology: { label: "Технологии", icon: Cpu },
  science: { label: "Наука", icon: FlaskConical },
  travel: { label: "Путешествия", icon: Plane },
  food: { label: "Еда", icon: UtensilsCrossed },
  sports: { label: "Спорт", icon: Dumbbell },
  music: { label: "Музыка", icon: Music },
  movies: { label: "Фильмы", icon: Film },
  books: { label: "Книги", icon: BookOpen },
  gaming: { label: "Игры", icon: Gamepad2 },
  art: { label: "Искусство", icon: Palette },
  business: { label: "Бизнес", icon: Briefcase },
  health: { label: "Здоровье", icon: HeartPulse },
  fashion: { label: "Мода", icon: Shirt },
  nature: { label: "Природа", icon: TreePine },
  history: { label: "История", icon: Landmark },
  photography: { label: "Фотография", icon: Camera },
  education: { label: "Образование", icon: GraduationCap },
  politics: { label: "Политика", icon: Megaphone },
  humor: { label: "Юмор", icon: Laugh },
  pets: { label: "Питомцы", icon: PawPrint },
};

export const INTEREST_KEYS = Object.keys(INTERESTS) as InterestType[];
